language: perl
perl:
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"

before_install:
  - npm install -g less
  - cpanm http://cpan.metacpan.org/authors/id/M/ML/MLEHMANN/common-sense-3.6.tar.gz
  # As of 2013-11-02 travis doesn't seem to find this one yet.
  - cpanm http://cpan.metacpan.org/authors/id/M/MA/MAKAMAKA/JSON-2.90.tar.gz
  - cpanm -n Devel::Cover::Report::Coveralls

script:
  - perl Makefile.PL && cover -test -report coveralls

notifications:
  email:
    recipients:
      - olaf@wundersolutions.com
    on_success: change
    on_failure: always
